#!/bin/sh
RESP=0
#Determine short name of script, which is the same name as the peer file
peerfile=`echo $0 | xargs -n1 basename`
#Extract the interface name from the filename (e.g. ppp0)
interface=`echo $peerfile | cut -d"-" -f2`

case $1 in
 "start" )
  echo "Launching VPN process"
  $0 go &
  echo "Process launched"
;;

 "go"  )
  echo "Waiting......."
  sleep 10
  PIDFILE="/var/run/$interface.pid"
  if [ -f "${PIDFILE}" ];
  then
   PID="`cat ${PIDFILE}`"
   if egrep vpn "/proc/${PID}/cmdline" 2>&1 > /dev/null;
   then
    echo "Already active!"
    exit 16
   fi
   echo "Removing PID file"
   rm -f "${PIDFILE}"
  fi
  echo -n $$ > "${PIDFILE}"
  echo "PID file created"
  echo "Attempting initial connect"
  pon $peerfile
  echo "Initial connection dropped"

  while [ 1 ];
  do
   echo "Attempting connect... "
   killall pptp 2>/dev/null
   sleep 2
   killall -9 pptp 2>/dev/null
   sleep 1
   pon $peerfile 
   echo "Connection dropped... "
   sleep 2
  done;
 ;;

 "debug"  )
  echo "Waiting......."
  sleep 10
  PIDFILE="/var/run/$interface.pid"
  if [ -f "${PIDFILE}" ];
  then
   PID="`cat ${PIDFILE}`"
   if egrep vpn "/proc/${PID}/cmdline" 2>&1 > /dev/null;
   then
    echo "Already active!"
    exit 16
   fi
   echo "Removing PID file"
   rm -f "${PIDFILE}"
  fi
  echo -n $$ > "${PIDFILE}"
  echo "PID file created"
  echo "Attempting initial connect"
  pon $peerfile
  echo "Initial connection dropped"

  while [ 1 ];
  do
   echo "Attempting connect... "
   killall pptp 2>/dev/null
   sleep 2
   killall -9 pptp 2>/dev/null
   sleep 1
   pon $peerfile
   echo "Connection dropped... "
   sleep 2
  done;
 ;;

"stop"   )

  VPNPID=`cat /var/run/$interface.pid`
  echo "Killing VPN PID $VPNPID"
  kill $VPNPID
  sleep 2
  kill -9 $VPNPID 2>/dev/null

  PPTPPID=`pidof -s pptp`
  echo "Killing PPTP PID $PPTPPID"
  kill $PPTPPID
  sleep 2
  kill -9 $PPTPPID
  sleep 2
  rm /var/run/$interface.pid
  echo "VPN Stopped"
 ;; 
* ) 
  echo " "
  echo "  PTPP VPN CLIENT" 
  echo "  --------" 
  echo " " 
  echo "   start  -  Starts the Client" 
  echo "   stop   -  Stops the Client" 
  echo "   go     -  Run the Client interactively (for debugging)" 
  echo "   debug  -  Run the Client interactively (in full debug mode)" 
  echo " " 
 ;; 
esac
return $RESP
