#! /bin/sh
# DSVR (Domain Specific VPN Router)
# Copyright 2013 Darran Boyd
#
# Licensed under the "Attribution-NonCommercial-ShareAlike" Vizsage
# Public License (the "License"). You may not use this file except
# in compliance with the License. Roughly speaking, non-commercial
# users may share and modify this code, but must give credit and 
# share improvements. However, for proper details please 
# read the full License, available at
#     http://vizsage.com/license/Vizsage-License-BY-NC-SA.html 
# and the handy reference for understanding the full license at 
#     http://vizsage.com/license/Vizsage-Deed-BY-NC-SA.html
#
# Unless required by applicable law or agreed to in writing, any
# software distributed under the License is distributed on an 
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied. See the License for the specific 
# language governing permissions and limitations under the License.
case "$1" in
  start)
    echo "Sleeping for 10s"
    sleep 10
    echo "Restarting"
    ifdown eth0 && ifup eth0
    echo "ETH0 Re-started"
    ;;
  stop)
    echo "Stop - NOT implemented"
    ;;
  *)
    echo "Usage: /etc/init.d/DB-restarteth0 {start|stop}"
    exit 1
    ;;
esac
exit 0
