#! /bin/sh
# DSVR (Domain Specific VPN Router)
# Copyright 2013 Darran Boyd
#
# Licensed under the "Attribution-NonCommercial-ShareAlike" Vizsage
# Public License (the "License"). You may not use this file except
# in compliance with the License. Roughly speaking, non-commercial
# users may share and modify this code, but must give credit and 
# share improvements. However, for proper details please 
# read the full License, available at
#     http://vizsage.com/license/Vizsage-License-BY-NC-SA.html 
# and the handy reference for understanding the full license at 
#     http://vizsage.com/license/Vizsage-Deed-BY-NC-SA.html
#
# Unless required by applicable law or agreed to in writing, any
# software distributed under the License is distributed on an 
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied. See the License for the specific 
# language governing permissions and limitations under the License.

PIDFILE="/var/run/dsvr.pid"
case "$1" in
  start)
    if [ -f "${PIDFILE}" ];
    then
     PID="`cat ${PIDFILE}`"
     if egrep dsvr "/proc/${PID}/cmdline" 2>&1 > /dev/null;
     then
      echo "Already Active!"
      exit 16
    fi
    echo "Removing PID file"
    rm -f "${PIDFILE}"
    fi
    echo -n $$ > "${PIDFILE}"
    echo "PID file created" 
    python /replacemewithsed/dsvr.py --interface 0.0.0.0 --file dsvr.ini -q
    echo "dsvr Started"
    ;;
  stop)
    PIDID=`cat ${PIDFILE}`
    pkill -9 -f dsvr.py
    rm -f "${PIDFILE}"
    echo "dsvr Stopped"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/dsvr {start|stop|restart}"
    exit 1
    ;;
esac
exit 0
