#! /bin/sh
PIDFILE="/var/run/dsvr.pid"
case "$1" in
  start)
    if [ -f "${PIDFILE}" ];
    then
     PID="`cat ${PIDFILE}`"
     if egrep dsvr "/proc/${PID}/cmdline" 2>&1 > /dev/null;
     then
      echo "Already Active!"
      exit 16
    fi
    echo "Removing PID file"
    rm -f "${PIDFILE}"
    fi
    echo -n $$ > "${PIDFILE}"
    echo "PID file created" 
    python /replacemewithsed/dsvr.py --interface 0.0.0.0 --file dsvr.ini -q
    echo "dsvr Started"
    ;;
  stop)
    PIDID=`cat ${PIDFILE}`
    pkill -9 -f dsvr.py
    rm -f "${PIDFILE}"
    echo "dsvr Stopped"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/dsvr {start|stop|restart}"
    exit 1
    ;;
esac
exit 0
